//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digisoft.Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bidding()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string JobUrl { get; set; }
        public string ProposalUrl { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int PlatformId { get; set; }
        public int AppliedUnderId { get; set; }
        public int DeveloperId { get; set; }
        public int ProjectTypeId { get; set; }
        public int TechnologyId { get; set; }
        public decimal Price { get; set; }
        public string Notes { get; set; }
        public int ConnectsUsed { get; set; }
        public System.DateTime AppliedOn { get; set; }
        public Nullable<int> TeamLeadId { get; set; }
        public Nullable<bool> GetReply { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AppliedUnder AppliedUnder { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual TeamLead TeamLead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
