//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digisoft.Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int JobId { get; set; }
        public System.DateTime BillingDate { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
    }
}
